import normalize from 'react-native-normalize';
import { ViewStyle, Dimensions } from 'react-native';

const height = Dimensions.get('window').height;

import color from '@styles/color';
import themeStyle from '@styles/theme.style';

export const homeStyle: any = {
  container: {
    flex: 1,
    backgroundColor: color.WHITE,
  } as ViewStyle,
  scrollView: {
    marginBottom: normalize(-20),
  },
  txtTitleHome: {
    fontSize: normalize(25),
    fontWeight: '700',
    fontFamily: themeStyle.FONT_BOLD,
    marinBottom: normalize(0),
    marginTop: normalize(8),
    color: color.MAIN,
  },
  viewTitleHome: {
    marginTop: normalize(10),
    marginHorizontal: normalize(24),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  txtName: {
    fontSize: normalize(25),
    fontWeight: '700',
    fontFamily: themeStyle.FONT_BOLD,
    color: color.BLACK,
    marinBottom: normalize(0),
    marginTop: normalize(8),
  },
  mapHome: {
    width: '100%',
    height: (height * 80) / 100,
    borderRadius: normalize(16),
    marginTop: normalize(16),
  },
  mapCheck: {
    width: '100%',
    height: (height * 50) / 100,
    borderRadius: normalize(16),
    // marginTop: normalize(16),
  },
  txtChoseFromMap: {
    fontSize: normalize(14),
    fontFamily: themeStyle.FONT_FAMILY,
    marginLeft: normalize(8),
    color: color.MAIN,
  } as ViewStyle,
  viewChooseFromMap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(12),
  } as ViewStyle,
  addressItem: {
    padding: normalize(8),
    borderBottomWidth: 1,
    borderBottomColor: color.SILVER,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: normalize(8),
  } as ViewStyle,
  titleAddressItem: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.BLACK,
    marginLeft: normalize(8),
    // paddingRight: normalize(16),
  },
  txtAddressItem: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.DUSTY_GRAY,
    marginLeft: normalize(8),
    marginTop: normalize(4),
    width: '60%',
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: normalize(8),
    marginBottom: normalize(16),
    paddingHorizontal: normalize(24),
  },
  actionItem: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtActionItem: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.BLACK,
    marginTop: normalize(4),
    textAlign: 'center',
    flexWrap: 'wrap',
    width: normalize(70), // giới hạn width, text sẽ wrap đẹp
  },
  banner: {
    height: normalize(50),
    borderRadius: normalize(16),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: normalize(8),
    marginHorizontal: normalize(24),
    marginBottom: normalize(24),
  },
  bannerText: {
    color: color.MAIN,
    fontSize: normalize(20),
    fontFamily: themeStyle.FONT_BOLD,
    fontWeight: '700',
  },
  weatherDetail: {
    fontSize: 12,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.DUSTY_GRAY,
    marginBottom: normalize(6),
  },
  iconActionItem: {
    width: normalize(50),
    height: normalize(50),
    borderRadius: normalize(25),
    backgroundColor: color.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  weatherCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: normalize(24),
    padding: normalize(8),
    paddingHorizontal: normalize(16),
    marginVertical: normalize(16),
    borderRadius: normalize(16),
  },
  weatherTemp: {
    fontSize: 40,
    fontFamily: themeStyle.FONT_BOLD,
    color: color.MAIN,
    fontWeight: '700',
  },
  surveyTitle: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_BOLD,
    color: color.BLACK,
    fontWeight: '700',
    marginBottom: normalize(4),
  },
  surveyDesc: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.DUSTY_GRAY,
    marginBottom: normalize(4),
  },
  surveyLink: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_BOLD,
    color: color.SUN_FLOWER,
    fontWeight: '700',
    marginTop: normalize(8),
  },
  surveyCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    flexDirection: 'row',
    alignItems: 'center',
    padding: normalize(16),
    marginHorizontal: normalize(24),
    borderRadius: normalize(16),
    marginBottom: normalize(16),
  },
  questionCard: {
    flexDirection: 'row',
    marginHorizontal: normalize(24),
    padding: normalize(16),
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    alignItems: 'center',
    marginBottom: normalize(16),
    borderRadius: normalize(16),
  },
  progressCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    padding: normalize(16),
    marginHorizontal: normalize(24),
    borderRadius: normalize(16),
    marginBottom: normalize(16),
  },
  titleProgressCard: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_BOLD,
    color: color.BLACK,
    fontWeight: '700',
    marginBottom: normalize(8),
    textAlign: 'center',
  },
  valueProgressCard: {
    fontSize: 18,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.BLACK,
    marginBottom: normalize(16),
    textAlign: 'center',
  },
  bgWaterPlant: {
    flex: 1,
    resizeMode: 'cover',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  backButton: {
    position: 'absolute',
    top: normalize(60),
    left: normalize(20),
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: normalize(16),
    padding: normalize(8),
    width: normalize(40),
    height: normalize(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletButton: {
    position: 'absolute',
    top: normalize(60),
    right: normalize(20),
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: normalize(16),
    padding: normalize(8),
    width: normalize(40),
    height: normalize(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  backText: {
    fontSize: 22,
    color: '#333',
    fontWeight: '600',
  },
  plantContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: normalize(50),
  },
  plant: {
    fontSize: 80,
  },
  waterButton: {
    backgroundColor: '#4FC3F7',
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: normalize(22),
    alignSelf: 'center',
    marginBottom: normalize(25),
    shadowColor: '#4FC3F7',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
  },
  waterText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  progressContainer: {
    height: 40,
    width: '70%',
    backgroundColor: '#eee',
    borderRadius: 100,
    overflow: 'hidden',
    alignSelf: 'center',
    marginBottom: normalize(30),
    justifyContent: 'center',
  },
  progressBar: {
    height: '100%',
    backgroundColor: color.MAIN,
    borderRadius: normalize(12),
  },
  progressText: {
    textAlign: 'center',
    color: '#333',
    fontSize: 15,
    alignSelf: 'center',
    position: 'absolute',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  rain: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    pointerEvents: 'none',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  sectionBody: {
    padding: 8,
    borderRadius: 8,
  },
  question: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#bbb',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  radioOuterActive: {
    borderColor: color.MAIN,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: color.MAIN,
  },
  radioLabel: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  inputSurvey: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#e3e3e3',
    borderRadius: 8,
    padding: 10,
    backgroundColor: '#fff',
  },
  starBox: {
    width: 46,
    height: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    marginRight: 8,
    marginTop: normalize(8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  starBoxActive: {
    borderColor: '#ffb400',
    backgroundColor: '#fff8e1',
  },
  starText: {
    fontSize: 18,
  },
  starNum: {
    fontSize: 12,
    color: '#333',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  ratingText: {
    fontSize: 22,
    fontWeight: '700',
    color: color.MAIN,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  ratingSubText: {
    fontSize: 13,
    color: '#555',
    marginTop: normalize(8),
    fontFamily: themeStyle.FONT_FAMILY,
  },
  ratingDetail: {
    alignItems: 'center',
    backgroundColor: color.LIGHT_GRAY,
    borderRadius: 12,
    paddingVertical: 12,
    flex: 1,
    marginHorizontal: 6,
  },
  ratingSamary: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 24,
  },
  ratingTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    fontFamily: themeStyle.FONT_BOLD,
  },
  ratingNumber: {
    fontSize: 48,
    fontWeight: '700',
    color: '#333',
    fontFamily: themeStyle.FONT_BOLD,
  },
  ratingStar: {
    fontSize: 20,
    color: '#666',
    marginBottom: 4,
    fontFamily: themeStyle.FONT_BOLD,
  },
  ratingUser: {
    width: normalize(60),
    textAlign: 'right',
    color: '#666',
    fontSize: 13,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  processRating: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(12),
  },
  processRatingNumber: {
    fontSize: 13,
    width: normalize(20),
    fontFamily: themeStyle.FONT_FAMILY,
  },
  processLine: {
    height: 8,
    borderRadius: 4,
    backgroundColor: color.MAIN,
  },
  processLineContainer: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#eee',
    overflow: 'hidden',
  },
};
