import { ViewStyle, Dimensions } from 'react-native';
import normalize from 'react-native-normalize';

import color from '@styles/color';
import themeStyle from '@styles/theme.style';

const { width } = Dimensions.get('window');

export const userStyle: any = {
  container: {
    flex: 1,
    backgroundColor: 'white',
  } as ViewStyle,
  scrollViewContent: {
    marginBottom: normalize(-300),
  },
  fastImage: {
    height: normalize(100),
    width: normalize(100),
    borderRadius: normalize(500),
    marginBottom: normalize(16),
    marginTop: normalize(16),
    alignSelf: 'center',
  },
  txtName: {
    fontSize: 22,
    fontWeight: '700',
    fontFamily: themeStyle.FONT_BOLD,
    color: color.MAIN,
    marinBottom: normalize(0),
    alignSelf: 'center',
    marginBottom: normalize(16),
  },
  titleFunction: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: themeStyle.FONT_BOLD,
    color: color.BLACK,
    marginBottom: normalize(16),
    marginLeft: normalize(28),
  },
  functionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(12),
  },
  functionCard: {
    marginBottom: normalize(16),
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(8),
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: normalize(16),
  },
  txtFunction: {
    fontSize: 15,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.BLACK,
    marginLeft: normalize(16),
  },
  txtVerion: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.DUSTY_GRAY,
    alignSelf: 'center',
    marginTop: normalize(16),
    marginBottom: normalize(50),
  },
  viewAdd: {
    alignItems: 'center',
    justifyContent: 'center',
    height: normalize(55),
    width: normalize(55),
    borderRadius: normalize(500),
    backgroundColor: color.MAIN,
    position: 'absolute',
    bottom: normalize(100),
    right: normalize(40),
    zIndex: 999,
  } as ViewStyle,
  viewEmpty: {
    flex: 1,
    marginTop: normalize(50),
    alignItems: 'center',
  } as ViewStyle,
  txtEmpty: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.DUSTY_GRAY,
  },
  itemJournal: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    padding: normalize(8),
    marginHorizontal: normalize(16),
    borderBottomWidth: 1,
    borderColor: color.DUSTY_GRAY,
    borderStyle: 'dashed',
  },
  txtJournalDate: {
    fontSize: 12,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.DUSTY_GRAY,
    marginBottom: normalize(8),
  },
  txtJournalContent: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.BLACK,
  },
  headerJournal: {
    backgroundColor: color.LIGHT_GRAY,
    paddingVertical: normalize(16),
    paddingHorizontal: normalize(16),
  },
  txtHeaderJournal: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_BOLD,
    color: color.MAIN,
  },
  rowJournalLine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(16),
    paddingRight: normalize(16),
  },
  txtJournalTitle: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.BLACK,
    marginLeft: normalize(8),
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(8),
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  infoValue: {
    fontSize: 13,
    fontFamily: themeStyle.FONT_BOLD,
  },
  infoLabel: {
    fontSize: 11,
    fontFamily: themeStyle.FONT_FAMILY,
    color: color.DUSTY_GRAY,
  },
  btnMonth: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: normalize(15),
    marginHorizontal: normalize(25),
  },
  txtMonth: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_BOLD,
    color: color.MAIN,
  },
  modelGoal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  viewModalGoal: {
    backgroundColor: '#fff',
    borderRadius: 16,
    width: '100%',
    padding: 20,
  },
  titleModalGoal: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 10,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  inputGoal: {
    borderWidth: 1,
    borderColor: color.MAIN,
    borderRadius: 10,
    padding: normalize(8),
    marginTop: normalize(8),
    fontSize: 14,
    height: normalize(50),
  },
  viewGoal: {
    borderWidth: 2,
    borderColor: color.MAIN,
    margin: normalize(16),
    padding: normalize(16),
    borderRadius: normalize(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleGoal: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: normalize(16),
    fontFamily: themeStyle.FONT_FAMILY,
  },
  txtValueGoal: {
    fontSize: 50,
    fontWeight: '600',
    color: color.MAIN,
    fontFamily: themeStyle.FONT_BOLD,
  },
  labelJournal: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: normalize(16),
    fontFamily: themeStyle.FONT_FAMILY,
  },
  viewCreateJournal: {
    paddingHorizontal: normalize(16),
  },
  optionContainer: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
    marginTop: normalize(8),
  },
  optionItem: {
    flexDirection: 'row' as const,
    padding: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#f9f9f9',
    width: '31%',
    marginBottom: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionItemFuel: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center',
    padding: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#f9f9f9',
    width: '48%',
  },
  selectedOption: {
    borderColor: '#99EBD1',
    backgroundColor: '#E8F8F5',
  },
  optionIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  optionText: {
    fontSize: 14,
    color: '#333',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  destinationList: {
    position: 'absolute',
    top: normalize(190),
    left: 10,
    right: 10,
    zIndex: 1,
    backgroundColor: '#fff',
    borderRadius: 5,
  },
  originList: {
    position: 'absolute',
    top: normalize(100),
    left: 10,
    right: 10,
    zIndex: 1,
    backgroundColor: '#fff',
    borderRadius: 5,
  },
  suggestionItem: {
    padding: 10,
    backgroundColor: '#f9f9f9',
    borderBottomWidth: 1,
    borderColor: '#eee',
    flexDirection: 'row',
  },
  infoTrip: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  textValueJournal: {
    fontSize: 20,
    fontWeight: '600',
    color: color.MAIN,
    fontFamily: themeStyle.FONT_BOLD,
    marginTop: normalize(16),
  },
  viewEditIcon: {
    position: 'absolute',
    bottom: normalize(8),
    left: width / 2 + 16,
    backgroundColor: color.MAIN,
    borderRadius: 20,
    padding: 6,
    alignSeft: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  txtSettingItem: {
    fontSize: 15,
    color: '#253255',
    marginLeft: normalize(16),
    fontFamily: themeStyle.FONT_FAMILY,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: normalize(13),
    backgroundColor: color.LIGHT_GRAY,
    margin: normalize(16),
    borderRadius: normalize(16),
    marginTop: normalize(16),
    marginBottom: normalize(0),
  },
  titleChangePassword: {
    fontFamily: themeStyle.FONT_FAMILY,
    textAlign: 'center',
    fontSize: 16,
    marginVertical: normalize(24),
    paddingHorizontal: normalize(8),
  },
  viewChart: {
    borderWidth: 1,
    borderColor: '#ccc',
    margin: normalize(16),
    padding: normalize(8),
    marginTop: normalize(0),
    borderRadius: normalize(12),
  },
  titleChart: {
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 16,
    fontWeight: '600',
    color: color.BLACK,
    marginBottom: normalize(8),
    marginTop: normalize(8),
    alignSelf: 'center',
  },
  itemReport: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(8),
    borderBottomWidth: 1,
    borderBottomColor: color.LIGHT_GRAY,
    marginHorizontal: normalize(16),
  },
  totalItemReport: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(8),
    borderBottomColor: color.LIGHT_GRAY,
    marginHorizontal: normalize(16),
    marginBottom:  normalize(32),
  },
  infoReport: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  nameReport: {
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 14,
  },
  percentReport: {
    fontSize: 14,
    color: color.DUSTY_GRAY,
    marginLeft: 8,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  valueReport: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: themeStyle.FONT_FAMILY,
    marginLeft: 'auto',
  },
  totalReport: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: color.MAIN,
    // marginTop: 12,
  },
  totalTextReport: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  iconReport: {
    width: normalize(30),
    backgroundColor: color.DUSTY_GRAY,
    height: normalize(30),
    marginHorizontal: normalize(16),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(12),
  },
};
